[features]
seeds = false
skip-lint = false
[programs.localnet]
sukasuka = "BBWxojjkikdbGWPQThCDSC7tHP5AYc6GMPcsNRPvzAjP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/oleksii/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
